"use client";
import Link from "next/link";
import { useState } from "react";
import { Archive, Bot, CheckCircle2, Database, Fingerprint, Loader2, ShieldCheck } from "lucide-react";

type RunResponse = { run_id:string; status:string; capsule_hash:string; walrus_blob_id:string; sui_certificate_id:string; sui_tx_digest:string; verify_url:string; capsule_url:string; blob_mode:string; certificate_mode:string; error?:string };
const steps=[['generating trace',Bot],['building capsule',Archive],['uploading to Walrus',Database],['certifying on Sui',Fingerprint],['verified',ShieldCheck]];
export function RunPanel(){const [run,setRun]=useState<RunResponse|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); async function start(){setLoading(true); setError(''); setRun(null); const res=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task_type:'ai_agent_trust_demo'})}); const json=await res.json(); setLoading(false); if(!res.ok){setError(json.error||'Run failed');return} setRun(json);} return <div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Demo agent</p><h1 className="mt-2 text-3xl font-semibold">RiskLens trust review run</h1><p className="mt-2 text-muted-foreground">Deterministic flow: trace, capsule, blob, certificate, verification.</p></div><button onClick={start} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={18}/>:<Bot size={18}/>}Start run</button></div><div className="mt-8 grid gap-3 md:grid-cols-5">{steps.map(([label,Icon],i)=><div key={String(label)} className={`rounded-xl border p-4 ${run||loading?'border-primary/40 bg-primary/5':'border-border bg-secondary'}`}><Icon className={run||loading?'text-primary':'text-muted-foreground'} size={20}/><p className="mt-3 text-sm font-medium">{String(label)}</p><p className="mt-1 text-xs text-muted-foreground">{run?'complete':loading && i<4?'processing':'waiting'}</p></div>)}</div>{error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{run&&<div className="mt-8 rounded-2xl border border-border bg-[#111111] p-5 text-[#fff7ed]"><div className="grid gap-4 md:grid-cols-2"><Field k="Run ID" v={run.run_id}/><Field k="Capsule hash" v={run.capsule_hash}/><Field k="Walrus blob ID" v={run.walrus_blob_id}/><Field k="Sui certificate" v={run.sui_certificate_id}/><Field k="Modes" v={`${run.blob_mode} blob / ${run.certificate_mode} certificate`}/><Field k="Tx digest" v={run.sui_tx_digest}/></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Link className="rounded-md bg-primary px-4 py-2 text-center font-semibold text-primary-foreground" href={run.verify_url}>Open verifier</Link><Link className="rounded-md border border-white/15 px-4 py-2 text-center font-semibold" href={run.capsule_url}>Inspect capsule</Link></div></div>}</div>}
function Field({k,v}:{k:string;v:string}){return <div><p className="text-xs uppercase tracking-[.16em] text-[#faae40]">{k}</p><code className="break-all text-sm text-white/80">{v}</code></div>}
